{% set version = "3.0.13" %}

package:
  name: jupyterlab_widgets
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyterlab_widgets/jupyterlab_widgets-{{ version }}.tar.gz
  sha256: a2966d385328c1942b683a8cd96b89b8dd82c8b8f81dda902bb2bc06d46f5bed
build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - jupyter-packaging
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
  run_constrained:
    - jupyterlab >=3,<5

test:
  imports:
    - jupyterlab_widgets
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - grep -iE "@jupyter-widgets/jupyterlab-manager.*OK" labextensions
  requires:
    - jupyterlab
    - m2-grep  # [win]
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jupyter-widgets/ipywidgets
  summary: JupyterLab extension providing HTML widgets
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jasongrout
    - SylvainCorlay
    - martinRenou
    - jtpio
    - bollwyvl
