# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "3.0.17"
  python_check_max: "3.14"

package:
  name: jupyterlab_widgets
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyterlab_widgets/jupyterlab_widgets-${{ version }}.tar.gz
  sha256: 6e61fe21ca8a66039180a5cc52a433e07279d2fee79c8be963e00d55193f17a8

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - hatch-jupyter-builder
    - hatchling
    - jupyterlab 4.*
    - pip
    - python ${{ python_min }}.*
    - yarn
  run:
    - python >=${{ python_min }}
  run_constraints:
    - jupyterlab >=4,<5

tests:
  - python:
      imports: jupyterlab_widgets
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - requirements:
      run:
        - jupyterlab
        - python ${{ python_min }}.*
    script:
      env:
        JS_NAME: "@jupyter-widgets/jupyterlab-manager"
      file: run_test.py

about:
  summary: JupyterLab extension providing HTML widgets
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/jupyter-widgets/ipywidgets

extra:
  recipe-maintainers:
    - jasongrout
    - SylvainCorlay
    - martinRenou
    - jtpio
    - bollwyvl
